// <auto-generated />
using System;
using EF.Core.Contexts.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.Core.Contexts.Migrations.BuaAmbulance
{
    [DbContext(typeof(BuaAmbulanceContext))]
    [Migration("20180726085304_addingSeedData")]
    partial class addingSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.Core.Entities.BuaAmbulance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Ambulances");

                    b.HasData(
                        new { Id = new Guid("a09c1e14-d823-4281-926d-345299696beb") },
                        new { Id = new Guid("7fa0d8be-83b2-45fa-b3ce-e40b6195beaa") },
                        new { Id = new Guid("7dc436a5-29b9-475d-a394-f97a691f74f3") },
                        new { Id = new Guid("e4fb1be6-4ba7-40c7-beef-e2b8c32751b6") },
                        new { Id = new Guid("4da90981-6a19-48a1-a6d0-c1f413dc748d") },
                        new { Id = new Guid("1849dfa8-9fac-4b0c-a63f-e3198935dc7b") },
                        new { Id = new Guid("dc8fabd1-09b6-427f-8454-2066a70d2828") },
                        new { Id = new Guid("c66f9fae-ea7c-43cf-b5bf-54f9164489f8") },
                        new { Id = new Guid("f5950a6f-a698-4393-a9a5-5441cd03b1f7") }
                    );
                });

            modelBuilder.Entity("EF.Core.Entities.Whiner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AmbulanceId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AmbulanceId");

                    b.ToTable("Whiners");

                    b.HasData(
                        new { Id = new Guid("e600cd73-a28d-4561-9f65-88c1d1d22ebb"), AmbulanceId = new Guid("a09c1e14-d823-4281-926d-345299696beb"), Name = "Mozzarella" },
                        new { Id = new Guid("d2060902-12c1-49e5-be5a-fda55ad4a53a"), AmbulanceId = new Guid("7fa0d8be-83b2-45fa-b3ce-e40b6195beaa"), Name = "Bulletto" },
                        new { Id = new Guid("6f1c9fd1-b47c-4df3-af1b-d6a16541475f"), AmbulanceId = new Guid("7dc436a5-29b9-475d-a394-f97a691f74f3"), Name = "Latte" },
                        new { Id = new Guid("da38fb3f-bbb6-4701-b50e-0a05de626fe1"), AmbulanceId = new Guid("e4fb1be6-4ba7-40c7-beef-e2b8c32751b6"), Name = "Strawberry Milk" },
                        new { Id = new Guid("717c411c-05a8-4bef-8537-f2d666349e56"), AmbulanceId = new Guid("4da90981-6a19-48a1-a6d0-c1f413dc748d"), Name = "Choco" },
                        new { Id = new Guid("bdbfb19e-5719-4e38-b287-2117227e33da"), AmbulanceId = new Guid("1849dfa8-9fac-4b0c-a63f-e3198935dc7b"), Name = "Soya" },
                        new { Id = new Guid("c7c83b08-dc7e-4cc7-beaf-83f4d4ae8bb0"), AmbulanceId = new Guid("dc8fabd1-09b6-427f-8454-2066a70d2828"), Name = "Leche" },
                        new { Id = new Guid("37c13f0a-db03-4732-a740-c5f57241482f"), AmbulanceId = new Guid("c66f9fae-ea7c-43cf-b5bf-54f9164489f8"), Name = "Half & Half" },
                        new { Id = new Guid("11610d8e-9f79-45d7-9cfc-fc80e2d44eaf"), AmbulanceId = new Guid("f5950a6f-a698-4393-a9a5-5441cd03b1f7"), Name = "Mou Mou" },
                        new { Id = new Guid("9cee4b48-c425-438e-bde6-04db490dad3b"), AmbulanceId = new Guid("f5950a6f-a698-4393-a9a5-5441cd03b1f7"), Name = "Miruku" }
                    );
                });

            modelBuilder.Entity("EF.Core.Entities.Whiner", b =>
                {
                    b.HasOne("EF.Core.Entities.BuaAmbulance", "Ambulance")
                        .WithMany("Whiners")
                        .HasForeignKey("AmbulanceId");
                });
#pragma warning restore 612, 618
        }
    }
}
