// <auto-generated />
using System;
using EF.Core.Contexts.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EF.Core.Contexts.Migrations.BuaAmbulance
{
    [DbContext(typeof(BuaAmbulanceContext))]
    [Migration("20180725205948_InitialBuaAmbulance")]
    partial class InitialBuaAmbulance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EF.Core.Entities.Ambulance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Ambulances");
                });

            modelBuilder.Entity("EF.Core.Entities.Whiner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AmbulanceId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AmbulanceId");

                    b.ToTable("Whiners");
                });

            modelBuilder.Entity("EF.Core.Entities.Whiner", b =>
                {
                    b.HasOne("EF.Core.Entities.Ambulance", "Ambulance")
                        .WithMany("Whiners")
                        .HasForeignKey("AmbulanceId");
                });
#pragma warning restore 612, 618
        }
    }
}
